### ISSUE TITLE
Need steps to integrate react application

### ISSUE THREAD

**Issue by Tamilarasanbe5** [Lightstreamer/Lightstreamer-lib-client-javascript#8]
Hi,
Any one knows how to integrate this package to react application.Please list out the steps to follow

Thanks,
Tamil.B

**Comment by acarioni** [comment]
Hello,

This [demo](https://demos.lightstreamer.com/?p=lightstreamer&t=client&sclienthtml=react) shows a template react application integrating Lightstreamer.

**Comment by Tamilarasanbe5** [comment]
@acarioni i got the project but in the code how to start the project.because we don't have any script file on the project

**Comment by Tamilarasanbe5** [comment]
@acarioni can you please tell me how to run the project.

Thanks,
Tamil.B

**Comment by acarioni** [comment]
In order to run the demo, you have to follow the instructions listed in the [Install section](https://github.com/Lightstreamer/Lightstreamer-example-StockList-client-react#install) of the Readme file.

In particular, you have 
(1) to get a copy of `lightstreamer.min.js` and put it in the folder `src/js`
(2) to install a Lightstreamer server on your machine.

You can skip step (2) and target directly the Lightstreamer demo server by opening the file `src/js/Constants.js` and changing the server address from `localhost:8080` to `push.lightstreamer.com`.

BTW, this is not the place to post this kind of questions. If you need support to use the Lightstreamer products, you should post on the user forum https://forums.lightstreamer.com/ instead.
